[package]
name = "rust-playground"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "HandsOnRustBook/dungeoncrawl",
  "HandsOnRustBook/flappy",
  "HandsOnRustBook/treehouse",
]
[dependencies]
